### ISSUE TITLE
Kernel 4.13.0-38.43 broke Ethernet support on Realtek cards

### ISSUE THREAD

**Issue by wowbaggerBR** [elementary/switchboard-plug-networking#119]
I received the uptade to this kernel and it broke my Ethernet support. And it's almost funny because I was pretty sure that it'd do this and I updated anyway.

And, sure enough, after the reboot the wired network options simply disappeared from the GUI, indicating a problem that I saw with another laptop equal to mine, but with Ubuntu 16.04 and an updated kernel.

`sudo lshw -c network -sanitize` showed me that the system was able to identify the Ethernet card, but no driver was listed as installed: it should had r8168 (proprietary) or r8169 installed.

Being well versed about woes regarding the driver for Realtek cards and more recent kernel versions, I've searched for the r8168/r8169 driver with:

`dkms status`

Sure enough, the r8168 was shown as "added".

Using `sudo dkms build r8168/8.041.00 -k "$(uname -r)/$(uname -p)"` in order to build it and install it with dkms install gave me all sorts of errors with the Kernel rejecting it - which I was expecting after seeing something like this in other laptop.

Is there anything I can do in order to fix this to run the more recent kernel or should I stick with the older one? I ask because I don't mind running the r8169, but I'm not sure if this is possible or easy to do.

**Comment by tintou** [comment]
Unfortunately I don't think that there is any action to take on our side: we don't have the hardware to test it, you can maybe try to report it in Ubuntu side.
Glad that you found a workaround!
