### ISSUE TITLE
Networks with multiple access points are shown as separate entries

### ISSUE THREAD

**Issue by Philip-Scott** [elementary/switchboard-plug-networking#97]
On Juno, networks with multiple access points are displayed as separate entries, which does not occur in Loki.

## Loki: 
![image](https://user-images.githubusercontent.com/10786508/36281319-e41243d0-1262-11e8-98a2-576cd139aa98.png)

## Juno: 
![screenshot from 2018-02-15 14 58 24](https://user-images.githubusercontent.com/10786508/36281013-ca7c840e-1261-11e8-9298-70d1909a520f.png)

I almost want to blame NM for this, because the plug is just reading the information that's available for us though d-bus. But there might be some config we can add instead of writing code to this plug and the indicator.

**Comment by tintou** [comment]
See related issue in wingpanel indicator:
https://github.com/elementary/wingpanel-indicator-network/issues/73

**Comment by fabianthoma** [comment]
According to @cassidyjames this is fixed in Loki daily builds.
