### ISSUE TITLE
meson regression: installation location of .so file wrong

### ISSUE THREAD

**Issue by decathorpe** [elementary/switchboard-plug-networking#98]
Installing to `/usr/network/libnetworking.so` is definitely wrong (on at least 2 levels).

**Comment by tintou** [comment]
Do you have switchboard past this commit ?
https://github.com/elementary/switchboard/commit/885d7b421795422f669387fcd398056e9467ebe1

**Comment by decathorpe** [comment]
I've tried to build it against the latest stable version. I'll try it again with the latest git master of switchboard.

**Comment by tintou** [comment]
Yep, that should be it, build the unrelease plug against the unrelease switchboard, I added there the required pkgconfig key to simplify future maintainance.

**Comment by decathorpe** [comment]
Ok, thanks!
